- name: archive web root
  command: tar -zcvf {{bkpfile}} {{root_dir}}  

- name: create bucket in s3
  s3: bucket=omnixbbackup mode=create aws_secret_key={{ec2_secret_key}} aws_access_key={{ec2_access_key}} region=eu-central-1
- name: upload backup to s3
  s3: bucket=omnixbbackup object={{bkpfile}} src={{bkpfile}} mode=put aws_secret_key={{ec2_secret_key}} aws_access_key={{ec2_access_key}} region=eu-central-1

- name: delete  backupfile
  file: path={{bkpfile}}  state=absent
