- name: install python mysql module
  pkgng: name=py27-MySQLdb state=present

- name:  mysqldump
  mysql_db: name={{dbname}} login_user={{dbusr}} login_password={{passwd}} login_host={{dbhost}} state=dump target={{bkpdir}}/{{dbname}}{{ ansible_date_time.date }}.sql.bz2

- name: create bucket in s3
  s3: bucket=omnixbbackup mode=create region=eu-central-1  aws_secret_key={{ec2_secret_key}} aws_access_key={{ec2_access_key}}

- name: upload backup to s3
  s3: bucket=omnixbbackup object={{bkpdir}}/{{dbname}}{{ ansible_date_time.date }}.sql.bz2 src={{bkpdir}}/{{dbname}}{{ ansible_date_time.date }}.sql.bz2 mode=put  aws_secret_key={{ec2_secret_key}} aws_access_key={{ec2_access_key}} region=eu-central-1

- name: delete backup file
  file: path={{bkpdir}}/{{dbname}}{{ ansible_date_time.date }}.sql.bz2 state=absent





  


